baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '1st Workshop on Templates'
theme = 'ananke'

site_logo = "img/logo.png"

# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-dark-blue"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
#featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-dark-blue-60"

[params.ananke.social.share]
networks = [
  "email",
  "facebook",
  "bluesky",
  "linkedin"
]

[params.ananke.social.follow]
networks = [
  "facebook",
  "bluesky",
  "linkedin"
]

[params.ananke.social.facebook]
username = "placeholder"
# profilelink = "https://www.facebook.com/placeholder"

[params.ananke.social.linkedin]
username = "placeholder"

[params.ananke.social.bluesky]
username = "placeholder"
